services:
  flask:
    build:
      context: ./python
      dockerfile: Dockerfile-flask
    container_name: flask
    volumes:
      - ./python/app:/app
    ports:
      - "8085:5000"
    environment:
      gemini_api_key: ${gemini_api_key}
      REMBG_CONTAINER_URL: ${REMBG_CONTAINER_URL}
      REMBG_CONTAINER_PORT: ${REMBG_CONTAINER_PORT}
    networks:
      - container-link
      # - kd-develop-2024-team-A_default

  tailwind:
    build:
      context: ./python
      dockerfile: Dockerfile-tailwind
    container_name: tailwind
    volumes:
      - ./python/app/static/css:/app/static/css
      - ./python/app/templates:/app/templates
    environment:
      - TAILWIND_MODE=${TAILWIND_MODE}
    tty: true

  rembg:
    build:
      context: ./python
      dockerfile: Dockerfile-rembg
    container_name: rembg
    # volumes:
    #   - ./python/app/static/uploads:/app/static/uploads
    #   - ./python/app/static/outputs:/app/static/outputs
    networks:
      - container-link
      # - kd-develop-2024-team-A_default
    ports:
      - "7047:7047"
    tty: true

networks:
  container-link:
    driver: bridge
