version: '3'

services:
  web:
    build: python
    ports:
      - "80:5000"
    environment:
      gemini_api_key: ${gemini_api_key}

    #   TZ: ${default_timezone}
    volumes:
      - ./python/app:/app
    # depends_on:
    #   - mysql
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
