FROM python:3.11-slim
WORKDIR /work
COPY ./rembg .
RUN pip install --upgrade pip
RUN pip install rembg Pillow requests
RUN apt update && apt install -y wget
RUN wget -P /root/.u2net/ https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx

CMD ["python", "function.py"]