# Dockerfile-tailwind
FROM node:20.18.0-alpine
WORKDIR /app
COPY ./app/static/css ./static/css
COPY tailwind-config.sh .
RUN npm i -D tailwindcss
# RUN npm install sharp rembg-node
RUN npx tailwindcss init
RUN sh tailwind-config.sh
CMD ["sh", "-c", "TAILWIND_MODE=watch npx tailwindcss -i /app/templates/input.css -o /app/static/css/style.css --watch --poll"]
# wsl2の問題でwatchが効かないのでpollをつける（以下参考文献）
# https://github.com/rails/tailwindcss-rails/pull/168
# CMD ["npx", "tailwindcss", "-i", "/app/templates/input.css", "-o", "/app/static/css/style.css", "--watch"]