# Dockerfile-tailwind
FROM node:alpine
WORKDIR /app
COPY ./app/static/css ./static/css
COPY tailwind-config.sh .
RUN npm i -D tailwindcss
RUN npx tailwindcss init
RUN sh tailwind-config.sh
CMD ["sh", "-c", "TAILWIND_MODE=watch npx tailwindcss -i /app/templates/input.css -o /app/static/css/style.css --watch --poll"]
# CMD ["npx", "tailwindcss", "-i", "/app/templates/input.css", "-o", "/app/static/css/style.css", "--watch"]