FROM python:3.11-slim
WORKDIR /app
COPY /app .
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# RUN apt update && apt install -y cowsay

# CMD ["python", "-u", "app.py"]
CMD ["gunicorn", "-w", "17", "-b", "0.0.0.0:8000", "--log-level", "debug", "app:app"]