FROM python:3.11
WORKDIR /app
COPY /app .
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN apt update && apt install -y cowsay

CMD ["python", "-u", "app.py"]