name: Merge develop to https

on:
  push:
    branches: [develop]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update develop branch
        run: git pull

      - name: Checkout https branch
        run: |
          git fetch origin https:https
          git checkout https

      - name: Merge develop into https
        run: git merge develop --allow-unrelated-histories

      - name: Push changes to https
        run: git push origin https
